// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Data;

#nullable disable

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ProdutoContext))]
    [Migration("20250315230252_SeedProdutos")]
    partial class SeedProdutos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProductAPI.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Estoque = 18,
                            Nome = "SSD",
                            Valor = 499.99m
                        },
                        new
                        {
                            Id = 101,
                            Estoque = 8,
                            Nome = "Placa de Vídeo",
                            Valor = 2300.99m
                        },
                        new
                        {
                            Id = 102,
                            Estoque = 12,
                            Nome = "Processador",
                            Valor = 800.99m
                        },
                        new
                        {
                            Id = 103,
                            Estoque = 22,
                            Nome = "Memória RAM",
                            Valor = 520.99m
                        },
                        new
                        {
                            Id = 104,
                            Estoque = 4,
                            Nome = "Monitor",
                            Valor = 1250.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
