name: ProductAPI - Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.10

    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
    - name: List files
      run: ls -R

    - name: Restaurar dependências
      run: dotnet restore

    - name: Compilar o projeto
      run: dotnet build --no-restore --configuration Release

    - name: Executar testes
      run: dotnet test --no-build --configuration Release --logger trx --results-directory "TestResults"

    - name: Publicar resultados dos testes
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: TestResults
